# Use root/example as user/password credentials
version: "3.1"

services:
  database:
    image: "mongo"
    container_name: "my-mongo-container_name"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    ports:
      - 27017:27017
